  frontend:
    ports:
      - "8080:8080"

  custom-nginx:
    image: nginx:alpine
    container_name: custom-nginx
    ports:
      - "8081:8080"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - default 