version: '3.8'
services:
  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    restart: always
    environment:
      - MONGO_URI=mongodb://mongo:27017/oyunlistem
      - JWT_SECRET=supersecretkey
      - PORT=5023
    ports:
      - 5023:5023
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    restart: always
    ports:
      - 3000:80
    depends_on:
      - backend

volumes:
  mongo-data: 