version: '3.8'
services:
  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    restart: always
    environment:
      - MONGO_URI=mongodb://mongo:27017/oyunlistem
      - JWT_SECRET=supersecretkey
      - PORT=5023
    ports:
      - 5023:5023
    depends_on:
      - mongo
    networks:
      - default

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3023:80"
    depends_on:
      - backend
    networks:
      - default
    volumes:
      - ./frontend/dist:/app/dist

  custom-nginx:
    image: nginx:alpine
    container_name: custom-nginx
    ports:
      - "8081:8080"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - default
    command: >
      sh -c "cp -r /usr/share/nginx/html/* /usr/share/nginx/html/ &&
              nginx -g 'daemon off;'"

volumes:
  mongo-data:

networks:
  default:
    driver: bridge 